# Generated by Django 2.2.3 on 2019-07-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0001_dish_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.FileField(blank=True, upload_to='dish_image'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='menu_id',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='emenu.Menu'),
        ),
    ]
