# Generated by Django 2.2.3 on 2019-07-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0002_auto_20190715_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dish_image'),
        ),
    ]
